import { createSlice } from "@reduxjs/toolkit";

// Initial state for the user slice, retrieves userStatus from localStorage or sets it to an empty string
const initialState = {
    userStatus: localStorage.getItem("userStatus") || "", // Retrieving userStatus from localStorage or setting it to an empty string
};

// Creating a user slice using createSlice function
const userSlice = createSlice({
    // Name of the slice, used to identify the slice in the Redux store
    name: "user",

    // Initial state of the slice
    initialState,

    // Reducers define how the state should be updated in response to actions
    reducers: {
        // updateUserStatus reducer function, responsible for updating the userStatus state and storing it in localStorage
        updateUserStatus(state, action) {
            // Updating userStatus in the state with the payload of the action
            state.userStatus = action.payload;

            // Storing updated userStatus in localStorage
            localStorage.setItem("userStatus", action.payload);
        },
    },
});

// Extracting action creators from the user slice
export const { updateUserStatus } = userSlice.actions;

// Exporting the reducer function generated by createSlice
export default userSlice.reducer;
